### ISSUE TITLE
Ravepay Gateway Upgrade

### ISSUE THREAD

**Issue by gladchinda** [kingflamez/WHMCS-Rave-payment-module#1]
Hello @mr-flamez, I am currently working on the RavePay payment gateway for WHMCS but I see that you did the one that is currently in use and so I thought I should reach out to you on a few stuffs. There seems to be an issue with the current WHMCS plugin as I was made to understand. Payments using the plugin are completed on the Rave side but the WHMCS wallet doesnn't get credited.

**Comment by gladchinda** [comment]
I also noticed that the WHMCS Source Code is kind of encrypted using Ioncube and I can't really inspect the source code for trails. Were you able to access the source code while you were working on the plugin? If yes, how where you able to do that?

**Comment by iolufemi** [comment]
+1

**Comment by kingflamez** [comment]
@gladchinda sadly I don't have access to a WHMCS installation again, so I can't work or upgrade WHMCS 🙁, but I added you as a collaborator, you can help to work on this

**Comment by kingflamez** [comment]
@gladchinda hey where you able to resolve it, and what do you mean by whmcs wallet

**Comment by kingflamez** [comment]
@gladchinda I just tested it and it worked fine

**Comment by hotoracle** [comment]
Good work and thank you for the plugin. 
Can we have the payment forms load into a modal rather than one with black background?

**Comment by kingflamez** [comment]
@hotoracle I will work on that, expect the upgrade before this night

**Comment by kingflamez** [comment]
@hotoracle You can load it into a modal now
